dist: trusty
sudo: required
language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.2
env:
  global:
    - MIX_ENV=test VERBOSE_TEST=true

before_script:
  - mkdir -p priv/data/mnesia-test
  - mix deps.compile

script:
  - mix compile --warnings-as-errors
  - mix coveralls
  - mix format --check-formatted
  - mix credo

branches:
  only:
    - master
